name: Build realms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-arm64
            pkg_target: aarch64
            tar_name: realms-linux-arm64.tar.gz
            flags: ""
          
          - os: macos-14
            arch: macos-arm64
            pkg_target: darwin
            tar_name: realms-macos-arm64.tar.gz
            flags: ""
          
          - os: ubuntu-latest
            arch: rpi3
            pkg_target: arm
            tar_name: realms-rpi3.tar.gz
            flags: "-Tlinux -Parm"

          - os: ubuntu-latest
            arch: odroid-c2
            pkg_target: aarch64
            tar_name: realms-odroid-c2.tar.gz
            flags: "-Tlinux -Paarch64"

    name: Build for ${{ matrix.arch }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Free Pascal and Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y fpc lazarus
          else
            brew install fpc lazarus
          fi

      - name: Compile Realms Engine
        run: |
          mkdir -p bin/${{ matrix.arch }}
          make clean || true
          make all FLAGS="${{ matrix.flags }}"
          cp launcher bin/${{ matrix.arch }}/
          cp -r Projects bin/${{ matrix.arch }}/

      - name: Create tarball
        run: |
          tar -czvf ${{ matrix.tar_name }} -C bin/${{ matrix.arch }} .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: ${{ matrix.tar_name }}
